openapi: 3.0.1
info:
  title: Appointment Service
  description: '!UNFINISHED! Spec for Appointment Service'
  version: 0.2.0

tags:
  - name: agency
    description: All cal.com objects with a connection a unique agency
  - name: user
    description: Everything related to a onBer user
paths:
  /user:
    post:
      tags:
        - user
      summary: Add a new user to cal.com with user object
      operationId: createUser
      requestBody:
        description: User object that needs to be added to cal.com
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OnberUser'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalcomUser'
  /user/{userId}/eventType:
    get:
      tags:
        - user
      summary: Get all eventTypes of user
      operationId: getAllEventTypesOfUser
      parameters:
        - name: userId
          in: path
          description: ID of onber user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfCalcomEventTypes'
    post:
      tags:
        - user
      summary: Add a new eventType to a user
      operationId: addEventTypeToUser
      parameters:
        - name: userId
          in: path
          description: ID of onber user
          required: true
          schema:
            type: string
      requestBody:
        description: EventType object that needs to be added to cal.com
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalcomEventType'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalcomEventType'
  /user/{userId}/booking:
    get:
      tags:
        - user
      summary: Get all bookings of a user
      operationId: getAllBookingsOfUser
      parameters:
        - name: userId
          in: path
          description: ID of onber user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfCalcomBookings'
  /user/{userId}/meetingLink:
    get:
      tags:
        - user
      summary: Get meeting booking link for user
      operationId: getUserMeetingLink
      parameters:
        - name: userId
          in: path
          description: ID of onber user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeetingLink'
  /agency/{agencyId}/eventTypes:
    get:
      tags:
        - agency
      summary: Get all eventTypes of agencys initial meeting team
      operationId: getAllEventTypesOfAgency
      parameters:
        - name: agencyId
          in: path
          description: ID of onber agency
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfCalcomEventTypes'
    post:
      tags:
        - agency
      summary: Add a new eventType to a agencys initial meeting team
      operationId: addEventTypeToAgency
      parameters:
        - name: agencyId
          in: path
          description: ID of onber agency
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: EventType object that needs to be added to cal.com
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalcomEventType'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalcomEventType'
  /agency/{agencyId}/initialMeetingLink:
    get:
      tags:
        - agency
      summary: Get initial meeting booking link for agency
      operationId: getInitialMeetingLink
      parameters:
        - name: agencyId
          in: path
          description: ID of agency
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeetingLink'
components:
  schemas:
    CalcomBooking:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        userId:
          type: integer
          format: int32
          example: 4
        eventTypeId:
          type: integer
          format: int32
          example: 9
        uid:
          type: string
          example: xiuzqXxXqQTaZSfiHBAtUQ
        title:
          type: string
          example: Meeting Type 2 between Foo and Bar
        startTime:
          type: string
          example: 2022-06-15T23:30:00.000Z
        endTime:
          type: string
          example: 2022-06-16T00:00:00.000
    ArrayOfCalcomBookings:
      type: array
      items:
        $ref: '#/components/schemas/CalcomBooking'
    CalcomUser:
      type: object
      properties:
        id:
          type: integer
          format: int32
        username:
          type: string
        name:
          type: string
        email:
          type: string
        emailVerified:
          type: string
          format: nullable
        bio:
          type: string
        avatar:
          type: string
        timeZone:
          type: string
        weekStart:
          type: string
        endTime:
          type: integer
          format: int32
        bufferTime:
          type: integer
          format: int32
        theme:
          type: string
          format: nullable
        defaultScheduleId:
          type: integer
          format: int32
        locale:
          type: string
        timeFormat:
          type: integer
          format: int32
        brandColor:
          type: string
        darkBrandColor:
          type: string
        allowDynamicBooking:
          type: boolean
        away:
          type: boolean
        createdDate:
          type: string
        verified:
          type: boolean
        invitedTo:
          type: string
          format: nullable
    OnberUser:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        name:
          type: string
        email:
          type: string
        agencyId:
          type: integer
          format: int64
          example: 1
    CalcomEventType:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        title:
          type: string
          example: 30 Min Meeting
        slug:
          type: string
          example: 30min
        length:
          type: integer
          format: int32
          example: 30
        hidden:
          type: boolean
          example: false
        position:
          type: integer
          format: int32
          example: 0
        userId:
          type: integer
          format: int32
          nullable: true
          example: 1
        teamId:
          type: integer
          format: int32
          nullable: true
          example: 1
        eventName:
          type: string
          format: nullable
        timeZone:
          type: string
          format: nullable
        periodType:
          type: string
          example: UNLIMITED
        periodStartDate:
          type: string
          format: nullable
        periodEndDate:
          type: string
          format: nullable
        periodDays:
          type: string
          format: nullable
        periodCountCalendarDays:
          type: string
          format: nullable
        requiresConfirmation:
          type: boolean
        recurringEvent:
          type: string
          format: nullable
        disableGuests:
          type: boolean
        hideCalendarNotes:
          type: boolean
        minimumBookingNotice:
          type: integer
          format: int32
          example: 120
        beforeEventBuffer:
          type: integer
          format: int32
          example: 0
        afterEventBuffer:
          type: integer
          format: int32
          example: 0
        schedulingType:
          type: string
          format: nullable
        price:
          type: integer
          format: int32
          example: 0
        currency:
          type: string
          example: usd
        slotInterval:
          type: string
          format: nullable
        successRedirectUrl:
          type: string
          format: nullable
        description:
          type: string
          format: nullable
        locations:
          type: string
          format: nullable
        metadata:
          type: string
          format: nullable
    ArrayOfCalcomEventTypes:
      type: array
      items:
        $ref: '#/components/schemas/CalcomEventType'
    MeetingLink:
      type: object
      properties:
        meetlingLink:
          type: string
          example: https://mydomain.local/myConsultant